/* this file automatically generated by the Makefile */
#define COMPILER "g++"
#define CXXFLAGS "-fno-omit-frame-pointer -D_GNU_SOURCE -march=native  -O3 -g -gdwarf-2 -std=c++11 -flto"
#define OPTIMIZE "-O3"
